tarballs:
  "vcpkg.tar.gz":
    url: https://github.com/microsoft/vcpkg/archive/2020.06.tar.gz
    sha1: 6be2cccbfa1e10958ead0fb60a11a3f1e07b06aa
  "ruby.tar.gz":
    url: https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.gz
    sha1: 76e25fce50a87f76a3ccd6d0fdd9b7c792400249
  "vc_redist.x64.exe":
    url: https://aka.ms/vs/16/release/vc_redist.x64.exe
    sha1: 837a49f9eaacda7c077a8bbea149a52d766b81c0
  "mdocml.zip":
    url: https://embedeo.org/ws/doc/man_windows/mdocml-1.13.1-win32-embedeo-02.zip
    sha1: 3024816df0e66393f54542b81c06af137f8f5f24
ver: 2.7.1p83
release: 3
